// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnintOhyVuqLFKN3cw83rlYmfiDwBVnXA',
    appId: '1:365686146716:web:3b6419f6732a10c8c50f59',
    messagingSenderId: '365686146716',
    projectId: 'notes-6b8a6',
    authDomain: 'notes-6b8a6.firebaseapp.com',
    storageBucket: 'notes-6b8a6.firebasestorage.app',
    measurementId: 'G-7TR8QGFMNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGuBVQ8N8vALvsfGZdSajqwLvlBGRDEHA',
    appId: '1:365686146716:android:94be225310bef397c50f59',
    messagingSenderId: '365686146716',
    projectId: 'notes-6b8a6',
    storageBucket: 'notes-6b8a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUeBBlwhpF_oKp8oZgzn0jwdZnTrHunGU',
    appId: '1:365686146716:ios:ed56aa68e8bc73a3c50f59',
    messagingSenderId: '365686146716',
    projectId: 'notes-6b8a6',
    storageBucket: 'notes-6b8a6.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );
}
